name: Generate pygame-ce documentation

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: '0 0 * * *' # runs at every 12AM UTC

jobs:
  download-pygame-ce:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    defaults:
      run:
        working-directory: ../pyga.me
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pygame-ce
        run: |
          python -m pip install --upgrade pip
          pip install pygame-ce pygithub
      - name: Clone and move docs
        run: |
          python utils/generate_docs.py
      - uses: EndBug/add-and-commit@v9
        with:
          message: Update documentation
          committer_name: GitHub Actions
          committer_email: actions@pyga.me
